version: '3.1'

services:

  postgres:
    image: postgres:14.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=training
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  wildfly-app:
    depends_on:
      - postgres
    image: wildfly-app
    ports:
      - "8080:8080"
      - "9990:9990"